CREATE TABLE film(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL,
    description CHAR(200),
    release_date DATE,
    duration INTEGER,
    mpa_id INTEGER REFERENCES mpa (id),
    rate INTEGER,
    CONSTRAINT constr_date CHECK ( release_date >= '1895-12-28' ),
    CONSTRAINT constr_duration CHECK ( duration > 0 )
);

CREATE TABLE genre_film(
    film_id INTEGER REFERENCES film (id),
    genre_id INTEGER REFERENCES genre (id)
);

CREATE TABLE genre(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR
);

CREATE TABLE mpa(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR
);

CREATE TABLE likes(
    film_id INTEGER REFERENCES film (id),
    user_id INTEGER REFERENCES users (id)
);

CREATE TABLE users(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL ,
    email VARCHAR NOT NULL ,
    login VARCHAR NOT NULL ,
    birthday DATE
);

CREATE TABLE user_friend(
    user_1 INTEGER REFERENCES users (id),
    user_2 INTEGER REFERENCES users (id)
);